
export const Data = [
    {
      day: 'Monday',
      schedule: [
        { time: '8AM - 9AM', course: 'CSC 483.1', venue: "mbs 22", lecturer: "Dr Oghenekaro" },
        { time: '9AM - 10AM', course: 'CSC 483.1' },
        { time: '10AM - 11AM', course: '' },
        { time: '11AM - 12PM', course: '' },
        { time: '12PM - 1PM', course: '' },
        { time: '1PM - 2PM', course: 'CSC 486.1' },
        { time: '2PM - 3PM', course: 'CSC 486.1' },
        { time: '3PM - 4PM', course: '' },
        { time: '4PM - 5PM', course: '' },
        { time: '5PM - 6PM', course: '' },
      ],
    },
    {
      day: 'Tuesday',
      schedule: [
        { time: '8AM - 9AM', course: 'CSC 480.1' },
        { time: '9AM - 10AM', course: 'CSC 482.1' },
        { time: '10AM - 11AM', course: 'CSC 482.1' },
        { time: '11AM - 12PM', course: '' },
        { time: '12PM - 1PM', course: '' },
        { time: '1PM - 2PM', course: 'CSC 483.1' },
        { time: '2PM - 3PM', course: '' },
        { time: '3PM - 4PM', course: '' },
        { time: '4PM - 5PM', course: '' },
        { time: '5PM - 6PM', course: '' },
      ],
    },
    {
      day: 'Wednesday',
      schedule: [
        { time: '8AM - 9AM', course: '' },
        { time: '9AM - 10AM', course: '' },
        { time: '10AM - 11AM', course: '' },
        { time: '11AM - 12PM', course: '' },
        { time: '12PM - 1PM', course: 'CSC 498.1' },
        { time: '1PM - 2PM', course: 'CSC 480.1' },
        { time: '2PM - 3PM', course: 'CSC 480.1' },
        { time: '3PM - 4PM', course: 'GES 400.1' },
        { time: '4PM - 5PM', course: '' },
        { time: '5PM - 6PM', course: '' },
      ],
    },
    {
      day: 'Thursday',
      schedule: [
        { time: '8AM - 9AM', course: '' },
        { time: '9AM - 10AM', course: '' },
        { time: '10AM - 11AM', course: 'CSC 496.1' },
        { time: '11AM - 12PM', course: 'CSC 481.1' },
        { time: '12PM - 1PM', course: '' },
        { time: '1PM - 2PM', course: '' },
        { time: '2PM - 3PM', course: '' },
        { time: '3PM - 4PM', course: '' },
        { time: '4PM - 5PM', course: '' },
        { time: '5PM - 6PM', course: 'CSC 482.1' },
      ],
    },
    {
      day: 'Friday',
      schedule: [
        { time: '8AM - 9AM', course: '' },
        { time: '9AM - 10AM', course: 'CSC 486.1' },
        { time: '10AM - 11AM', course: 'CSC 498.1' },
        { time: '11AM - 12PM', course: 'CSC 496.1' },
        { time: '12PM - 1PM', course: 'CSC 481.1' },
        { time: '1PM - 2PM', course: '' },
        { time: '2PM - 3PM', course: '' },
        { time: '3PM - 4PM', course: '' },
        { time: '4PM - 5PM', course: 'GES 400.1' },
        { time: '5PM - 6PM', course: '' },
      ],
    },
]
